name: Build and Release AppImage

on:
  push:
    tags:
      - "v*"

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y fuse libfuse2 wget file

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: |
          cargo build --release

      - name: Download AppImage tool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/icons

          cp target/release/git-tree AppDir/usr/bin/

          # icon
          cp assets/git-tree.png AppDir/git-tree.png

          # desktop file
          cp git-tree.desktop AppDir/

      - name: Create AppRun
        run: |
          echo '#!/bin/sh
          exec "$APPDIR/usr/bin/git-tree"' > AppDir/AppRun
          chmod +x AppDir/AppRun

      - name: Build AppImage
        run: |
          ./appimagetool-x86_64.AppImage AppDir

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.AppImage"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
